Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../", "/get"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    bash /get/14.04.sh
  SHELL
end
